import Navbar from "@/components/Navbar/Navbar";
import "./globals.css";
import { Mulish } from 'next/font/google'; // Importar la fuente

// Cargar la fuente
const MulishFont = Mulish({
  subsets: ['latin'],  // Usar el subconjunto latino
  weights: ['400', '500', '600', '700', '800'], // Cargar todos los pesos disponibles
  styles: ['normal', 'italic'],  // Cargar los estilos normal e itálico
  display: 'swap',  // Usar "swap" para evitar el "FOIT" (Flash of Invisible Text)
});

export const metadata = {
  title: "Goles de Instituto",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={MulishFont.className}>
        <Navbar />
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}